---
title: "Concepts in Mechanics"
format: 
  html:
    toc: true
  pdf:
    toc: true
    number-sections: true
    colorlinks: true
    self-contained: true
editor: source
---

# The Four-Step Problem Solving Method {#fourstepmethod}

1. Determine what key concepts will help you solve the problem

2. Gather your information -- draw a picture, choose a coordinate system, identify "givens" in the problem statement (which are allowed to be in your answer), and determine your goal (what quantity you are solving for and any special conditions for it)

3. Solve: find appropriate equations (hint: your key concepts will help a lot here), and use those equations and math tools to eliminate all unknowns and lead to your answer.

4. Assess your answer. Check units and use some logical reasoning to defend your answer (or explain why it's wrong). Some methods you could use for the reasoning includes making predictions and seeing if your result matches those predictions, relating the answer to something you know (e.g. plugging in specific numbers and checking if they match real-world scenarios), and evaluating the equation (check limits and special cases, make sure it does what you expect)

# Physics Concepts {#concepts}

::: panel-tabset
## Kinematics

Position, velocity, and acceleration and the time derivatives/integrals that relate them

Special types of kinematics:

  - Expressing position, velocity, and acceleration in polar coordinates
  - Constant speed, fixed length, and constant acceleration motion 

## Forces

Newton's first law and inertial frames

Newton's second law and relating forces to motion

Newton's third law and force-related interactions between objects

In addition, we have seen the following forces:

  - Gravity (on a planet)
  - Universal Gravitation (Gravity in space)
  - Tension
  - Push and pull forces
  - Normal force
  - Static friction (three cases: definitely not moving, maybe going to move, on the verge of moving)
  - Kinetic friction
  - Velocity-dependent forces (drag, etc)
  - Spring force

## Collisions and Interactions

Impulse and change in momentum

Conservation of linear momentum

Collisions

  - Elastic
  - Inelastic
  - Perfectly inelastic (stick together)
  - Explosion (reverse perfectly inelastic)


## Energy

Work and kinetic energy

Work done by conservative v. nonconservative forces

Potential energy

Conservation of mechanical energy

## Rotation

Angular momentum of a particle

Angular momentum of an extended object

Torque and Newton's 2nd Law for Rotation

Rotational kinetic energy

Conservation of angular momentum


:::

# Math Tools {#mathtools}

::: panel-tabset
## Approximations

Using Taylor/MacLauren series when dealing with something small

[List of common series](https://en.wikipedia.org/wiki/Taylor_series#List_of_Maclaurin_series_of_some_common_functions)

## Curvilinear Coordinate Systems

Working in polar coordinates, including:

  - Time derivatives of vectors in polar coordinates
  - Time dependence of unit vectors in polar coordinates
  - Translating between Cartesian and polar coordinates

## Integrals

Separating and integrating simple ODEs

[Common integrals and derivatives](chrome-extension://efaidnbmnnnibpcajpcglclefindmkaj/https://tutorial.math.lamar.edu/pdf/common_derivatives_integrals.pdf)

:::